Added Table-Stateful & Table-Stateless
public-ui/public-ui.github.io pull request #250
Opened 2024-10-30 08:52 UTC by AlexanderSchmidtCE

2024-11-06 10:37 UTC, deleonio approved these changes

2024-11-06 10:39 UTC, deleonio requested changes
Wir brauchen das bitte noch auf English. In diesem Verzeichnis noch auf Englisch machen: https://github.com/public-ui/public-ui.github.io/tree/main/i18n/en/docusaurus-plugin-content-docs/current/30-components

@sdvg Kannst Du Alex das bitte erklären.

Es ist korrekt, dass wir aktuell noch keine englische Doku bei den Komponenten haben. Wir haben aber für alle Komponenten eine englische mdx die dann die readme.md auf Deutsch importiert.

2024-11-11 09:10 UTC, sdvg commented
@deleonio 

> Wir haben aber für alle Komponenten eine englische mdx die dann die readme.md auf Deutsch importiert.

Mit der Erklärung hat es für mich Sinn ergeben, das scheint mir aber nicht der Fall zu sein. Die Table wäre tatsächlich die erste Datei in [`30-components`](https://github.com/public-ui/public-ui.github.io/tree/main/i18n/en/docusaurus-plugin-content-docs/current/30-components), neben der index-Datei. Es werden automatisch die deutschsprachigen Seiten angezeigt, wenn keine Übersetzung existiert.

Aus Gründen der Konsistenz würde ich die Datei lieber wieder entfernen, wenn niemand Veto einlegt @AlexanderSchmidtCE.

2024-11-11 09:12 UTC, sdvg requested changes

2024-11-11 09:12 UTC, sdvg commented on docs/30-components/31-table/index.mdx
> +Die **TableStateless**-Komponente ist für die reine Darstellung der KoliBri-Tabelle verantwortlich. Sortierung und Paginierung werden von der Tabelle nicht automatisch übernommen
Die Unterscheidung trifft für mich noch nicht 100% den Punkt.
Formulierungsvorschlag:

```
Die **TableStateful**-Komponente ist darauf ausgelegt, große Datenmengen übergeben zu bekommen und übernimmt automatisch Funktionen wie Paginierung und Sortierung nach Tabellenspalten.

Die **TableStateless**-Komponente hingegen ist ausschließlich für die Darstellung zuständig. Ihr wird jeweils nur die darzustellende Teildatenmenge übergeben, während Sortierung und Filterung der Daten außerhalb der Komponente stattfinden und über die von der Komponente emittierten Events gesteuert werden können.
```

2024-11-11 09:12 UTC, sdvg commented on docs/30-components/31-table/index.mdx
> +Ausführlichere Informationen zur Nutzung findet sich auf der jeweiligen Seite.
```suggestion
Ausführlichere Informationen zur Nutzung finden sich auf der jeweiligen Seite.
```

2024-11-11 09:12 UTC, sdvg commented on docs/30-components/31-table/index.mdx
> +<Readme />
Oder wollen wir die Legacy Tabelle auch direkt auf eine neue Seite packen? Was denkst du, @AlexanderSchmidtCE?

Struktur könnte dann so aussehen:

```
Table
-- TableStateful
-- TableStateless
-- Table (Deprecated)
```

2024-11-11 09:12 UTC, sdvg commented on docs/30-components/31-table/table-stateful.mdx
> +title: Table-Stateful
```suggestion
title: TableStateful
```

Hier würde ich mich lieber an den bestehenden Seiten orientieren und den Original Komponentennamen in PascalCase-Schreibweise beibehalten.

Ebenfalls in der description und für die andere Seite.

2024-11-11 09:29 UTC, AlexanderSchmidtCE commented on docs/30-components/31-table/index.mdx
> +<Readme />
Die Idee mit dem eigenen Unterpunkt für die Deprecated Table gefällt mir.
Wirkt für mich sauberer, wenn in der Überkategorie keine Komponente direkt beschrieben wird, sondern nur einen Überblick.

Die Readme, die eingebunden ist enthält bereits die Info, dass Table deprectated ist.
![image](https://github.com/user-attachments/assets/4a1d4269-eec0-412e-bce9-aac3cc6add93)

2024-11-11 14:22 UTC, sdvg requested changes

2024-11-11 14:22 UTC, sdvg commented on docs/30-components/31-table/index.mdx
> +Es gibt drei Varianten der Tabelle: <kol-link _label="KolTable" _href="table/table"></kol-link>, <kol-link _label="KolTableStateful" _href="table/table-stateful"></kol-link> und <kol-link _label="Kol
Hier steht "drei" Varianten, im nächsten Satz wieder "beide".

Ich würde KolTable hier einfach weglassen, wird ja im übernächsten Abschnitt erwähnt.

```suggestion
Es gibt drei zwei der Tabelle: <kol-link _label="KolTable" _href="table/table"></kol-link>, <kol-link _label="KolTableStateful" _href="table/table-stateful"></kol-link> und <kol-link _label="KolTableStateless" _href="table/table-stateless"></kol-link>.
```

2024-11-11 14:22 UTC, sdvg commented on docs/30-components/31-table/index.mdx
> +<kol-badge _color="#fb4509" _label="Deprecated"></kol-badge> **Table** ist veraltet, bitte stattdessen <kol-link _label="KolTableStateful" _href="table/table-stateful"></kol-link> verwenden, die API
```suggestion
<kol-badge _color="#fb4509" _label="Deprecated"></kol-badge> **KolTable** ist veraltet, bitte stattdessen <kol-link _label="KolTableStateful" _href="table/table-stateful"></kol-link> verwenden, die API und Funktionalität sind identisch.
```

Um mögliche Irritationen zu vermeiden :)

2024-11-11 14:22 UTC, sdvg commented on package.json
> +		"@public-ui/themes": "2.2.0-alpha.0",
Hier müssen wir zur gegebenen Zeit noch auf die stabile `2.2.0` aktualisieren.

Bis dahin den Kommentar bitte stehen lassen und nicht resolven.

2024-11-16 09:03 UTC, deleonio requested changes
Wenn man ein fehlerhaftes Formular absendet und die Fehlerliste oben kommt, dann muss der Fokus auf die Fehlerliste wechseln.

<img width="907" alt="image" src="https://github.com/user-attachments/assets/7ece13e8-2496-4c27-9370-583069195b89">

Das ist aktuell nicht so. Bitte mal klären, ob unsere Fehlerliste am Form das automatisch machen sollen (ich denke schon), oder ob es die App-Devs wissen müssen.

FYI: @laske185, @cbraehmig

2024-11-20 13:45 UTC, deleonio requested changes
Ich möchte, dass jede Komponente einen eigenen Eintrag in der Menü-Leiste hat. Nicht alles unter Table verstecken.

@AlexanderSchmidtCE bitte hochpriorisieren. Danke

2024-11-21 10:56 UTC, laske185 commented on docs/30-components/table.mdx
> +	<kol-badge _color="#fb4509" _label="Deprecated"></kol-badge>KolTable ist veraltet, bitte stattdessen <kol-link _label="KolTableStateful" _href="table/table-stateful"></kol-link> verwenden, die API u
Link korrigieren `_href="table-stateful">`

2024-11-21 11:35 UTC, AlexanderSchmidtCE commented on docs/30-components/table.mdx
> +	<kol-badge _color="#fb4509" _label="Deprecated"></kol-badge>KolTable ist veraltet, bitte stattdessen <kol-link _label="KolTableStateful" _href="table/table-stateful"></kol-link> verwenden, die API u
ist korrigiert

2024-11-21 12:10 UTC, deleonio requested changes

2024-11-21 12:10 UTC, deleonio commented on docs/30-components/table-stateful.mdx
> +<kol-alert _type="warning" _variant="card">
Der Text sollte dann jetzt auch raus.

2024-11-21 12:10 UTC, deleonio commented on docs/30-components/table-stateless.mdx
> +<kol-alert _type="warning" _variant="card">
Der Text sollte dann jetzt auch raus.

2024-11-21 12:10 UTC, deleonio commented on docs/30-components/table.mdx
> +Über das Attribut **`_pagination`** kann optional eine Vielzahl zusätzlicher Properties zur Steuerung der Pagination übergeben werden. Die genaue Beschreibung der Optionen ist auf der Seite <kol-link
Link ist defekt

2024-11-21 12:10 UTC, deleonio commented on docs/30-components/span.mdx
Span kann raus.

2024-11-23 10:40 UTC, merged