Update component events documentation
public-ui/public-ui.github.io pull request #269
Opened 2024-12-20 13:59 UTC by sdvg

2025-01-14 11:05 UTC, laske185 requested changes

2025-01-14 11:05 UTC, laske185 commented on i18n/en/docusaurus-plugin-content-docs/current/20-concepts/03-events.mdx
> +description: todo
Auch hier entweder eine Beschreibung oder entfernen.

2025-01-15 07:12 UTC, sdvg commented on docs/20-concepts/03-events.mdx
> +description: todo
Danke! Habe deinen Formulierungsvorschlag so übernommen.

2025-01-15 07:13 UTC, laske185 approved these changes

2025-01-15 07:24 UTC, merged