3079 live editor code formatierung
public-ui/public-ui.github.io pull request #96
Opened 2023-05-09 07:38 UTC by Wolfram-Zell

2023-05-09 07:59 UTC, deleonio commented
Mach mal bitte sicherheitshalber ein `npm run build`

2023-05-09 07:59 UTC, deleonio requested changes
Mach mal bitte sicherheitshalber ein `npm run build`

2023-05-09 09:44 UTC, Wolfram-Zell commented
> Mach mal bitte sicherheitshalber ein `npm run build`
'Der Befehl "cp" ist entweder falsch geschrieben oder konnte nicht gefunden werden.'
-> "cp" ist unix (funktioniert aber auch in Powershell), ersetzen mit "copy" gibt 'Syntaxfehler.'

2023-05-11 05:43 UTC, deleonio requested changes
We can reuse the changes from this PR: https://github.com/public-ui/public-ui.github.io/pull/101/files

2023-05-16 04:15 UTC, merged